apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: booking-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: booking
  endpoints:
    - port: http
      path: /metrics
      interval: 15s