apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking-container
        image: flightagentic-booking-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000