apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - port: 80
      name: http
      targetPort: 3000
      nodePort: 30003